import json
import os
import subprocess

import click
from click import secho

from tfanalyze.change import Change, ChangeAction, from_entry

"""
Main CLI entrypoint for tfanalyze.
"""


@click.command()
@click.argument("plan")
@click.option("--show-no-op", is_flag=True, default=False, help="Show no-op changes.")
@click.option(
    "--destroy-only", is_flag=True, default=False, help="Show only deletion changes."
)
@click.option(
    "--update-only", is_flag=True, default=False, help="Show only update changes."
)
def tfanalyze(
    plan: str, show_no_op: bool, destroy_only: bool, update_only: bool
) -> None:
    """
    Summarize Terraform plan changes.
    """
    parsed_plan = _load(plan)
    changes = _parse_changes(parsed_plan)
    _summarize(changes, destroy_only, show_no_op, update_only)


def _summarize(
    changes: list[Change], destroy_only: bool, show_no_op: bool, update_only: bool
):
    """
    Summarize Terraform plan changes.

    :param changes: List of Change objects representing the plan changes
    :param destroy_only: Whether to show only destroy changes.
    :param show_no_op: Whether to include no-op changes in the summary.
    :param update_only: Whether to show only update changes.
    """
    # For every change in the plan, print the action and address
    for change in changes:
        # Perform filtering based on flags
        if not show_no_op and change.change_action == ChangeAction.NOOP:
            continue

        if destroy_only and change.change_action != ChangeAction.DESTROY:
            continue

        if update_only and change.change_action != ChangeAction.UPDATE:
            continue

        secho(change.change_action.name, fg=change.change_action.value, nl=False)
        secho(f" {change.address}")
        # Print updated properties
        if change.change_action == ChangeAction.UPDATE:
            for key, (old, new) in change.diff_properties().items():
                secho(f"  {key}: {old} -> {new}", fg="yellow")


def _load(plan: str) -> dict:
    """
    Load a Terraform plan file into a Python dictionary.
    Optionally pretty-print plan JSON.

    :param plan: Path to plan file, generated by running `terraform plan -out=plan.tfplan`.
    :return:
    """
    if not os.path.exists(plan):
        secho(f"File {plan} could not be found.", fg="red")
        exit(1)

    try:
        output = subprocess.run(
            ["terraform", "show", "-json", plan], check=True, capture_output=True
        )
        try:
            return json.loads(output.stdout)
        except json.JSONDecodeError:
            secho("Failed to parse Terraform plan JSON output.", fg="red")
            exit(1)

    except FileNotFoundError:
        secho("Terraform is not installed or not available in PATH.", fg="red")
        exit(1)

    except subprocess.CalledProcessError as e:
        secho("Failed to load Terraform plan.", fg="red")
        secho(f"\n{e.stderr.decode()}", fg="red")
        exit(1)


def _parse_changes(parsed_plan: dict) -> list[Change]:
    """
    Parse Terraform plan changes to the dedicated dataclass.
    :param parsed_plan: The plan dictionary.
    :return: list of Change class instances.
    """
    return [from_entry(entry) for entry in parsed_plan["resource_changes"]]
