import json
import os
import subprocess

import click
from click import secho

from tfanalyze.change import Change, ChangeAction, from_entry

"""
Main CLI entrypoint for tfanalyze.
"""


@click.command()
@click.version_option(package_name="tfanalyze")
@click.argument("plan")
@click.option(
    "--exclude",
    "-e",
    "exclude",
    multiple=True,
    type=click.Choice([action.name.lower() for action in ChangeAction]),
    help="Exclude a change type from the output. Can be repeated, e.g. -e noop -e destroy.",
)
@click.option(
    "--tofu",
    is_flag=True,
    default=False,
    help="Use OpenTofu instead of Terraform to read the plan.",
)
def tfanalyze(plan: str, exclude: tuple[str, ...], tofu: bool) -> None:
    """
    Summarize Terraform plan changes.
    """
    parsed_plan = _load(plan, tofu)
    changes = _parse_changes(parsed_plan)
    excluded_actions = {ChangeAction[action.upper()] for action in exclude}
    _summarize(changes, excluded_actions)


def _summarize(changes: list[Change], excluded_actions: set[ChangeAction]):
    """
    Summarize Terraform plan changes.

    :param changes: List of Change objects representing the plan changes
    :param excluded_actions: Change types to omit from the output.
    """
    # For every change in the plan, print the action and address
    for change in changes:
        if change.change_action in excluded_actions:
            continue

        secho(change.change_action.name, fg=change.change_action.value, nl=False)
        secho(f" {change.address}")
        # Print updated properties
        if change.change_action == ChangeAction.UPDATE:
            for key, (old, new) in change.diff_properties().items():
                _render_diff(key, old, new)


def _render_diff(key: str, old, new) -> None:
    """
    Render a single property diff. Scalar values are rendered on one line;
    multi-line or structured values (dicts, lists) are pretty-printed and
    rendered as a block so nested changes stay readable.
    """
    old_str = _stringify(old)
    new_str = _stringify(new)

    if "\n" not in old_str and "\n" not in new_str:
        secho(f"  {key}: ", nl=False)
        secho(old_str, fg="red", nl=False)
        secho(" -> ", nl=False)
        secho(new_str, fg="green")
        return

    secho(f"  {key}:")
    for line in old_str.splitlines():
        secho(f"    - {line}", fg="red")
    for line in new_str.splitlines():
        secho(f"    + {line}", fg="green")


def _stringify(value) -> str:
    """
    Render a property value for diffing. Dicts and lists are pretty-printed
    as indented JSON so structured changes (e.g. tags, policies) don't get
    flattened into an unreadable single line.
    """
    if isinstance(value, (dict, list)):
        return json.dumps(value, indent=2, sort_keys=True)
    return str(value)


def _load(plan: str, tofu: bool = False) -> dict:
    """
    Load a Terraform plan file into a Python dictionary.
    Optionally pretty-print plan JSON.

    :param plan: Path to plan file, generated by running `terraform plan -out=plan.tfplan`.
    :param tofu: Whether to use the OpenTofu binary instead of Terraform.
    :return:
    """
    if not os.path.exists(plan):
        secho(f"File {plan} could not be found.", fg="red")
        exit(1)

    binary = "tofu" if tofu else "terraform"

    try:
        output = subprocess.run(
            [binary, "show", "-json", plan], check=True, capture_output=True
        )
        try:
            return json.loads(output.stdout)
        except json.JSONDecodeError:
            secho("Failed to parse Terraform plan JSON output.", fg="red")
            exit(1)

    except FileNotFoundError:
        secho(
            f"{binary.capitalize()} is not installed or not available in PATH.",
            fg="red",
        )
        exit(1)

    except subprocess.CalledProcessError as e:
        secho("Failed to load Terraform plan.", fg="red")
        secho(f"\n{e.stderr.decode()}", fg="red")
        exit(1)


def _parse_changes(parsed_plan: dict) -> list[Change]:
    """
    Parse Terraform plan changes to the dedicated dataclass.
    :param parsed_plan: The plan dictionary.
    :return: list of Change class instances.
    """
    return [from_entry(entry) for entry in parsed_plan["resource_changes"]]
