version: '3'
tasks:
  fmt:
    desc: Run formatting
    cmds:
      - uv run black tfanalyze
      - uv run isort tfanalyze
      - uv run autoflake --in-place --remove-all-unused-imports --expand-star-import tfanalyze/*.py

  test:
    desc: Run tests
    cmds:
      - uv run coverage run -m pytest
      - uv run coverage html
      - uv run coverage xml -o test/coverage.xml
      - uv run genbadge coverage -i test/coverage.xml -o test/coverage.svg

  publish:
    desc: Create a release
    dotenv:
      - .env
    cmds:
      - rm -rf dist
      - uv build
      - uv publish